services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=form_management
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  form_management_api:
    build:
      context: .
      dockerfile: Form-Management.Api/Dockerfile
    image: form-management.api
    container_name: form-management.api
    ports:
      - "10000:10000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_HTTP_PORTS=10000
      - DATASOURCE_URL=Server=postgres;Port=5432;Database=form_management;User Id=postgres;Password=postgres;
      - CORS_ALLOWED_ORIGINS=http://localhost:5000
    depends_on:
      - postgres

  form_management_client:
    build:
      context: Form-Management.Client
      dockerfile: Dockerfile
      args:
        - VITE_USERS_URL=http://localhost:10000/api/users
    image: form-management.client
    container_name: form-management.client
    ports:
      - "5000:5000"
    environment:
      - ALLOWED_CLIENT_HOSTS=localhost
    depends_on:
      - form_management_api

volumes:
  postgres-data: