services:
  form_management_api:
    build:
      context: .
      dockerfile: Form-Management.Api/Dockerfile
    image: form-management.api
    container_name: form-management.api
    ports:
      - "10000:10000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_HTTP_PORTS=10000
      - DATASOURCE_URL=DB_STRING
      - CORS_ALLOWED_ORIGINS=http://localhost:5000
  
  form_management_client:
    build:
      context: Form-Management.Client
      dockerfile: Dockerfile
      args:
        - VITE_USERS_URL=http://localhost:10000/api/users
    image: form-management.client
    container_name: form-management.client
    ports:
      - "5000:5000"
    depends_on:
      - form_management_api